---
apiVersion: v1
kind: Secret
metadata:
  name: azure-sp-creds
  namespace: vault-hashicorp
  labels:
    app.kubernetes.io/name: vault-raft-operator
    app.kubernetes.io/component: credentials
type: Opaque
stringData:
  AZURE_CLIENT_ID: "your-client-id-here"
  AZURE_TENANT_ID: "your-tenant-id-here"
  AZURE_CLIENT_SECRET: "your-client-secret-here"
