services:
  vault:
    image: hashicorp/vault
    command: ["server"]
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./deploy/vault:/vault/config:rw
      - vault_data:/vault/file:rw
    restart: unless-stopped
    ports:
      - "8200:8200"

volumes:
  vault_data:
